### ISSUE TITLE
Should the name include the term forwarder?

### ISSUE THREAD

**Issue by willjgriff** [1Hive/time-lock-app#5]
ASFAIK this app is exclusively for forwarding evmscripts on the condition of some deposit being locked. Should it have forwarder in the name to better describe it's functionality? eg lock-forwarder or deposit-forwarder?

**Comment by lkngtn** [comment]
I'm not sure, I had originally labeled forwarders as such, but this will implement a UI for viewing locks and withdrawing. So its acting as both an App that a user would interact with directly, and as a forwarder which they would only interact with through the signer panel when interacting with a different app. 

but I agree that forwarder is a more descriptive (though technical name). I think the crux would be whether we would want this in apm as "lock.open.aragonpm.eth" or "lock-forwarder.open.aragonpm.eth".

**Comment by burrrata** [comment]
Going through the code to write docs and `lock-forwarder` would help to make it immediately clear what the lock-app is doing. It locks tokens, then forwards an intent. No lock, no forward. Also fits nicely with the infographic of the dotted line between the user facing apps and the apps that manage tokens. 

While the user will be able to interact with the app in multiple ways, I think that adding the word forwarder to the name makes it more clear overall what's happening.
